[package]
name = "ecspanse"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "ecspanse"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.27.0"
itertools = "0.10"
rayon = "1.7"
